/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package addressbook.actions;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.util.MessageResources;

import addressbook.forms.SearchForm;
import addressbook.Constants;

@SuppressWarnings("unused")
public class SearchAction extends AbstActionBase {
	private Log log=LogFactory.getLog(this.getClass().getName());
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchForm SearchForm = (SearchForm) form;// TODO Auto-generated method stub
	
		Locale locale=getLocale(request);
		MessageResources messages=getResources(request);
		
		ActionErrors errors=new ActionErrors();
		String name=SearchForm.getName();
		String phone=SearchForm.getPhone();
		String address=SearchForm.getAddress();
		
		if(!errors.isEmpty()){
			saveErrors(request,errors);
			return(new ActionForward(mapping.getInput()));
		}
		String strSql=new String("SELECT * FROM "+Constants.TABLENAME+" WHERE ");
		if (!name.equals(""))
			strSql = strSql + "name LIKE '"+ name +"%' AND";
		if (!phone.equals(""))
			strSql = strSql + " phone LIKE '"+ phone +"%' AND";
		if (!address.equals(""))
			strSql = strSql + " address LIKE '"+ address +"%'";
		else
		    strSql = strSql.substring(0,strSql.length()-3);
		
		strSql=strSql+" ORDER BY NAME";
		HttpSession session=request.getSession();
		
		if(log.isDebugEnabled()){
			log.debug("SearchAction session="+session);
			log.debug("SearchAction strSql="+strSql);
		}
			
		session.setAttribute(Constants.SQLSTMT_KEY, strSql); 
		return (mapping.findForward(Constants.FORWARD_SUCCESS));  
	}
}