DROP table if EXISTS ADDRESSBOOK_TABLE;
create table ADDRESSBOOK_TABLE (
	id int(10) NOT NULL AUTO_INCREMENT,
	name varchar(255) not NULL,
	phone varchar(255) not null,
	address varchar(255) not null,
	PRIMARY KEY(id)
)ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8;

INSERT INTO ADDRESSBOOK_TABLE VALUES(1,'Wang','56671234','Beijing,Haidian');
INSERT INTO ADDRESSBOOK_TABLE VALUES(2,'Zhang','45664568','Shanghai,Pudong');
INSERT INTO ADDRESSBOOK_TABLE VALUES(3,'Cheng','56643456','Tianjing');
INSERT INTO ADDRESSBOOK_TABLE VALUES(4,'Zhao','56789988','Hainan');
INSERT INTO ADDRESSBOOK_TABLE VALUES(5,'Cao','56498543','Heibei');
